version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - todo-app-network

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - todo-app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-app-network

volumes:
  mongo-data:

networks:
  todo-app-network:
    driver: bridge
